# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [8]:
print(x.size)
print(x.itemsize)
print(x.size * x.itemsize)
print(x.nbytes)

10
8
80
80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [9]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [10]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [11]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [12]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [13]:
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [14]:
arr=[1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [15]:
z=np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [19]:
x=np.random.random((3,3,3))
x

array([[[0.7630024 , 0.98694218, 0.5768314 ],
        [0.47700372, 0.45546807, 0.2587779 ],
        [0.59371963, 0.21654255, 0.43376753]],

       [[0.57901907, 0.4169738 , 0.9129893 ],
        [0.110471  , 0.60698625, 0.03791718],
        [0.61927027, 0.57890868, 0.64344722]],

       [[0.40833198, 0.00531964, 0.21192571],
        [0.7907065 , 0.86552651, 0.79894001],
        [0.60449665, 0.09835314, 0.87131889]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [22]:
x=np.random.random((10,10))
y,z=x.min(),x.max()
print(x)
print(y,z)

[[7.57935894e-01 3.29088865e-01 4.97315035e-01 7.18069918e-01
  5.46775158e-01 9.22353210e-01 9.37052366e-01 4.53805030e-01
  4.64015111e-01 8.82673080e-02]
 [4.12213960e-01 3.45258931e-01 9.12958289e-01 9.75384893e-01
  6.60935200e-01 5.02843252e-01 8.74644871e-01 6.21598977e-01
  6.85516158e-01 9.86051397e-01]
 [8.62727613e-01 3.31208387e-01 3.64758030e-01 5.13401316e-01
  7.95240959e-02 6.90547870e-02 5.93250403e-01 2.53184555e-01
  5.88386119e-01 3.25527039e-01]
 [5.73060925e-01 3.93073778e-01 4.43692430e-01 7.79450844e-01
  9.32989971e-01 8.86656753e-01 9.31408133e-01 1.38234632e-01
  3.08341764e-01 3.99791072e-01]
 [5.77445360e-01 2.86147942e-01 5.29898222e-01 3.93962276e-01
  4.08395362e-01 2.95139215e-01 2.99525173e-01 3.41153415e-01
  5.03416121e-01 7.65500895e-01]
 [2.50221190e-02 2.02916797e-01 4.15580075e-01 8.24232419e-01
  9.09047246e-01 2.89588572e-02 6.08460556e-02 1.50274468e-01
  7.85748262e-02 2.50895150e-01]
 [6.69536494e-01 7.99038140e-01 7.47197552e-01 5.42737304e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [23]:
x=np.random.random(30)
print(x)
print(x.mean())

[0.79181863 0.76265251 0.72574137 0.1469166  0.61465076 0.63209932
 0.62985159 0.52133687 0.38983689 0.71064422 0.29172637 0.31529175
 0.92457486 0.52352603 0.67785457 0.20725836 0.84219268 0.55652016
 0.2534442  0.16322928 0.72537437 0.0576539  0.41945012 0.17402378
 0.93125257 0.05586798 0.12170058 0.97136998 0.34652887 0.69078605]
0.5058391735181457


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [24]:
x=np.ones(30).reshape(5,6)
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [25]:
x=np.ones((3,3))
x=np.pad(x,pad_width=1,mode="constant",constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [29]:
print("nan")
print(False)
print(False)
print("nan")
print(False)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [27]:
x=np.diag([1,2,3,4],k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [28]:
x=np.ones((3,3))
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [30]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [34]:
x=np.tile(np.array([[0,1],[1,0]]),(4,4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [37]:
x=np.random.random((5,5))
y=x-x.min()
z=x-x.max()
print(y/z)

[[-5.03002594e-02 -9.02011924e-01 -3.87386680e+00 -3.16037234e+02
  -6.14741802e-01]
 [            inf -5.47068324e-02 -5.91773411e+00 -9.28499135e-01
  -1.69693792e+00]
 [-3.03962968e+00 -1.60368974e+00 -1.10108950e+00 -8.40527214e-02
  -0.00000000e+00]
 [-1.01612253e+01 -4.80615694e-01 -1.15256060e+00 -1.09306874e-01
  -3.03600362e-01]
 [-5.40745027e-01 -9.81970640e-01 -1.60706460e+00 -1.04379161e+00
  -8.74132110e-01]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [41]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [38]:
x=np.dot(np.ones((5,3)),np.arange(1,7).reshape(3,2))
x

array([[ 9., 12.],
       [ 9., 12.],
       [ 9., 12.],
       [ 9., 12.],
       [ 9., 12.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [40]:
x=np.arange(1,11)
m=(x>3)&(x<8)
x[m]*=-1
x

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [5]:
print(10)
print(10)

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [44]:
print("z<z>z")

z<z>z


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [45]:
print("the first and second expressions results in typeerror")
print(np.array([np.nan]).astype(int).astype(float))

the first and second expressions results in typeerror
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [47]:
arr = np.random.random((5,5))
arr = np.round(arr,2)
print(arr) 

[[0.1  0.09 0.8  0.69 0.59]
 [0.18 0.65 0.76 0.35 0.3 ]
 [0.21 0.67 0.3  0.54 0.92]
 [0.09 0.19 0.31 0.06 0.73]
 [0.75 0.43 0.07 0.09 0.84]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [48]:
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = [1, 3, 4]
print(np.intersect1d(ar1,ar2))

[1 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [49]:
# # Suicide mode on
# defaults = np.seterr(all="ignore")
# Z = np.ones(1) / 0

# # Back to sanity
# _ = np.seterr(**defaults)

# An equivalent way, with a context manager:

# with np.errstate(divide='ignore'):
#     Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [50]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [4]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2022-06-29 2022-06-30 2022-07-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [52]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [53]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [54]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[1. 4. 1. 0. 0. 5. 1. 5. 5. 9.]
[1. 4. 1. 0. 0. 5. 1. 5. 5. 9.]
[1. 4. 1. 0. 0. 5. 1. 5. 5. 9.]
[1 4 1 0 0 5 1 5 5 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [55]:
x=np.zeros(25).reshape(5,5)
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [7]:
def gen():
  for ele in range(10):
    yield ele
x=np.fromiter(gen(),dtype=float,count=-1)
print(x)   

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [8]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [12]:
x=np.random.random(10)
x.sort()
print(x)

[0.33044024 0.41241891 0.60096277 0.67411646 0.68002776 0.71875357
 0.77422009 0.79875084 0.84218485 0.89290296]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [13]:
import functools as ft
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [14]:
A=np.random.randint(10,15,5)
B=np.random.randint(10,15,5)
eq=np.allclose(A,B)
print(eq)
print(np.array_equal(A,B))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [16]:
x=np.arange(10)
x.flags.writeable=False
x[3]=15
print(x)
#gives valueerror because we have set x.flags.writeable is False

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [17]:
z= np.random.randint(0,9,(10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[3.60555128 0.98279372]
 [3.         1.57079633]
 [8.54400375 1.21202566]
 [8.         1.57079633]
 [4.         1.57079633]
 [3.         0.        ]
 [4.47213595 1.10714872]
 [7.21110255 0.98279372]
 [8.06225775 1.05165021]
 [9.89949494 0.78539816]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [18]:
ar1 = np.random.random(10)
print(ar1)
ar1[ar1.argmax()] = 0
print(ar1)

[0.59045416 0.07021104 0.16070216 0.2219521  0.15234363 0.77794259
 0.93302381 0.88766029 0.72735602 0.59879157]
[0.59045416 0.07021104 0.16070216 0.2219521  0.15234363 0.77794259
 0.         0.88766029 0.72735602 0.59879157]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [19]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [20]:
Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)

Y = np.tile(Y,(10,1))

X  = np.tile(X,(10,1)).T


C = 1/(X - Y)
C

array([[0.14285714, 0.09090909, 0.125     , 0.1       , 0.07142857,
        0.11111111, 0.09090909, 0.1       , 0.09090909, 0.1       ],
       [0.16666667, 0.1       , 0.14285714, 0.11111111, 0.07692308,
        0.125     , 0.1       , 0.11111111, 0.1       , 0.11111111],
       [0.125     , 0.08333333, 0.11111111, 0.09090909, 0.06666667,
        0.1       , 0.08333333, 0.09090909, 0.08333333, 0.09090909],
       [0.14285714, 0.09090909, 0.125     , 0.1       , 0.07142857,
        0.11111111, 0.09090909, 0.1       , 0.09090909, 0.1       ],
       [0.1       , 0.07142857, 0.09090909, 0.07692308, 0.05882353,
        0.08333333, 0.07142857, 0.07692308, 0.07142857, 0.07692308],
       [0.33333333, 0.14285714, 0.25      , 0.16666667, 0.1       ,
        0.2       , 0.14285714, 0.16666667, 0.14285714, 0.16666667],
       [0.125     , 0.08333333, 0.11111111, 0.09090909, 0.06666667,
        0.1       , 0.08333333, 0.09090909, 0.08333333, 0.09090909],
       [0.33333333, 0.14285714, 0.25     

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [21]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [23]:
 #p.set_printoptions(threshold= np.nan)
Z = np.zeros((25,25))
print(Z) 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [24]:
arr = np.random.uniform(0,10,10)
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print(arr[ind])

[4.1391908  4.5228627  0.69608827 1.01656971 5.29758166 9.33376193
 9.65270959 0.98502707 7.25380428 4.05655945]
5.297581659367973


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [25]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [2]:
import numpy as np
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.2652232  0.53523457 ... 0.34337671 0.80530097 0.81641189]
 [0.2652232  0.         0.72452437 ... 0.57780025 0.54102759 0.55477384]
 [0.53523457 0.72452437 0.         ... 0.22897167 1.22161777 1.24933762]
 ...
 [0.34337671 0.57780025 0.22897167 ... 0.         1.1092674  1.12871886]
 [0.80530097 0.54102759 1.22161777 ... 1.1092674  0.         0.05470465]
 [0.81641189 0.55477384 1.24933762 ... 1.12871886 0.05470465 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [4]:
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [5]:
from io import StringIO

 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [6]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])
    
    

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [7]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [8]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)



[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [9]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

[[ 0.41470795 -0.18369111 -0.35646096 -0.18310884  0.26162865  0.13978207
   0.07048529  0.17455328 -0.19871269 -0.13918363]
 [ 0.30797222  0.10851901  0.20167123 -0.41284732 -0.408324    0.43150606
  -0.49352418  0.44135438  0.08374707 -0.26007449]
 [-0.47815443  0.04789316 -0.34173322 -0.35725018  0.11308849  0.27626904
   0.00169153  0.11290623  0.28821636  0.33707302]
 [ 0.05556372  0.10185659 -0.19038804 -0.20152953 -0.21770173  0.47781305
   0.43125073 -0.38828539 -0.44839117  0.37981178]
 [ 0.18531708  0.00551546 -0.193056    0.3107093   0.05242925 -0.32555737
  -0.15116896 -0.1698833  -0.01754876  0.3032433 ]]


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [10]:
Z = np.random.randint(0,10,(5,5))
print(Z)

print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[9 5 1 9 8]
 [0 3 2 1 4]
 [2 1 4 4 8]
 [8 7 8 6 4]
 [5 8 9 4 8]]
[[5 8 9 4 8]
 [8 7 8 6 4]
 [9 5 1 9 8]
 [0 3 2 1 4]
 [2 1 4 4 8]]
[[9 9 1 5 8]
 [0 1 2 3 4]
 [2 4 4 1 8]
 [8 6 8 7 4]
 [5 4 9 8 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [12]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [13]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


0.5001591027659612


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [14]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [15]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [2]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[2. 4. 4. 2. 3. 4. 2. 1. 3. 5.]
[3. 7. 7. 3. 5. 7. 3. 1. 5. 9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [3]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [3]:
import numpy as np
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)



64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [4]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

[[50 58 56 27]
 [45 65 61 53]
 [51 41 53 57]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [5]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.53675416 0.44298324 0.63162509 0.65617133 0.59525977 0.53593881
 0.51842582 0.29675959 0.594253   0.5682426 ]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [6]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.diag(np.dot(A,B)))

[2.0637846  0.4581219  2.12724106 0.58763424 1.1605023 ]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [7]:
z=np.array([1,2,3,4,5])
n=3
res=np.zeros(len(z)+(len(z)-1)*n)
res[::n+1]=z
print(res)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [8]:
A = np.ones((5,5,3))
B = 4*np.ones((5,5))
print(A * B[:,:,None])

[[[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [10]:
x=np.random.randint(10,50,(5,5))
print(x)
x[[1,2]]=x[[2,1]]
print(x)

[[43 46 44 17 30]
 [36 40 36 47 32]
 [33 44 11 31 25]
 [40 29 22 47 32]
 [17 23 12 13 31]]
[[43 46 44 17 30]
 [33 44 11 31 25]
 [36 40 36 47 32]
 [40 29 22 47 32]
 [17 23 12 13 31]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [11]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 59) ( 0, 60) ( 2, 13) ( 2, 33) ( 9, 21) ( 9, 53) (12, 86) (12, 94)
 (13, 33) (16, 20) (16, 86) (20, 86) (21, 53) (25, 68) (25, 91) (30, 96)
 (32, 38) (32, 44) (36, 68) (36, 90) (38, 44) (59, 60) (68, 90) (68, 91)
 (78, 81) (78, 99) (81, 99) (86, 94) (96, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [12]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [13]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [14]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [15]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.80588638, -0.37724878,  0.39862907,  0.39607488,  0.85268068,
       -0.14285887, -0.24071036,  0.32583063, -0.93726948,  0.94735143,
       -0.71692896, -0.17364715, -0.11302778,  0.60504921, -0.14652745,
       -0.20082334,  0.40346703, -0.66953816, -0.96887724,  0.21856576,
       -0.83252542,  0.86557427,  0.38579061, -0.70244829,  0.77181965,
        0.39709936, -0.22884211, -0.94843979, -0.84494502,  0.43328899,
       -0.67566863, -0.98125989, -0.44232427,  0.28089126,  0.31867301,
        0.63089283,  0.83606621, -0.51095269,  0.7677962 , -0.51238947,
        0.30136382, -0.10031205,  0.35059785,  0.58950664, -0.39805022,
       -0.41270105, -0.4583015 ,  0.87369498,  0.45799949, -0.92814412,
        0.45596458, -0.61361591, -0.3443022 , -0.0876794 , -0.56174915,
       -0.22468983,  0.49009496, -0.96917975,  0.53225835,  0.4148382 ,
       -0.35453055,  0.67877144,  0.93729595,  0.32303487,  0.74405971,
       -0.89666985,  0.43273   ,  0.98258662,  0.34555145,  0.12

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [16]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[5.14761753 3.23031802 6.19954468 4.7626529  2.56257206 1.10155604
 4.82217496 0.7771739  0.43463973 0.08087592]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [17]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.57132966  4.7038118   3.56701464  3.69188645  2.12985879 10.53494321
  10.55414137 11.7812652   0.83119326  2.05901286]
 [ 7.03683698  2.28222394  6.12042564  7.94627329  8.77848316 14.17358392
  15.77101157 15.0451174   4.63115422  9.88430604]
 [ 7.47977421 12.53989996  1.20515534  1.78911605  5.84877556  1.73269621
   2.09175057  2.92451647  9.0718532   1.01676596]
 [ 5.77204568  0.28122437  8.1472852   6.37946407  7.25703108 16.60082985
  16.19543569 17.92872269  5.64596742  4.14797771]
 [ 2.43465956  7.7752848   4.62813966  5.74999236  0.89981548  7.96976668
   7.72660207  9.28375199  1.71736804  4.35726331]
 [ 2.40712185  7.90046854  7.6087157   8.64323128  0.92543458  8.75192931
   8.10173083 10.15787092  0.59493069  7.16295096]
 [10.41350031 15.35657133  3.6989697   0.36061898  8.74262055  1.66626
   1.08000472  0.51767013 12.65633559  0.07661991]
 [ 6.89344328 12.41832362  7.90130645 10.45754251  5.42406026  4.59594156
   3.73095644  6.06289716  1.72250835  9.37252   ]
 [ 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [7]:
from numpy.lib import stride_tricks

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [8]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [9]:
x = np.random.randint(0,10,50)
print(np.bincount(x).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [10]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[0 0 1]
   [3 4 3]
   [3 1 1]]

  [[0 1 2]
   [4 3 0]
   [1 1 1]]

  [[1 2 4]
   [3 0 2]
   [1 1 2]]

  [[2 4 3]
   [0 2 3]
   [1 2 0]]

  [[4 3 0]
   [2 3 1]
   [2 0 0]]

  [[3 0 3]
   [3 1 3]
   [0 0 4]]

  [[0 3 3]
   [1 3 0]
   [0 4 4]]

  [[3 3 2]
   [3 0 1]
   [4 4 4]]]


 [[[3 4 3]
   [3 1 1]
   [1 1 1]]

  [[4 3 0]
   [1 1 1]
   [1 1 2]]

  [[3 0 2]
   [1 1 2]
   [1 2 0]]

  [[0 2 3]
   [1 2 0]
   [2 0 3]]

  [[2 3 1]
   [2 0 0]
   [0 3 3]]

  [[3 1 3]
   [0 0 4]
   [3 3 1]]

  [[1 3 0]
   [0 4 4]
   [3 1 4]]

  [[3 0 1]
   [4 4 4]
   [1 4 0]]]


 [[[3 1 1]
   [1 1 1]
   [1 4 2]]

  [[1 1 1]
   [1 1 2]
   [4 2 3]]

  [[1 1 2]
   [1 2 0]
   [2 3 2]]

  [[1 2 0]
   [2 0 3]
   [3 2 1]]

  [[2 0 0]
   [0 3 3]
   [2 1 0]]

  [[0 0 4]
   [3 3 1]
   [1 0 4]]

  [[0 4 4]
   [3 1 4]
   [0 4 0]]

  [[4 4 4]
   [1 4 0]
   [4 0 1]]]


 [[[1 1 1]
   [1 4 2]
   [0 3 1]]

  [[1 1 2]
   [4 2 3]
   [3 1 3]]

  [[1 2 0]
   [2 3 2]
   [1 3 4]]

  [[2 0 3]
   [3 2 1]
   [3 4 3]]

  [[0 3 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [11]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  4 12 11  9]
 [ 4  3 14  9 14]
 [12 14  5 42 14]
 [11  9 42  0  8]
 [ 9 14 14  8  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [12]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [13]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [14]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])


print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [15]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))    

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [16]:
Z = np.array([("Ravi", 2.5, 3),
              ("Prakash", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Ravi', 2.5, 3) (b'Prakash', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [19]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


1 loop, best of 5: 3.74 s per loop
10 loops, best of 5: 140 ms per loop
10 loops, best of 5: 120 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [20]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [21]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[3 2 3]
 [1 0 4]
 [0 3 3]
 [2 0 0]
 [3 4 1]
 [4 4 3]
 [2 3 4]
 [3 1 2]
 [0 1 3]
 [2 0 3]]
[[3 2 3]
 [1 0 4]
 [0 3 3]
 [2 0 0]
 [3 4 1]
 [4 4 3]
 [2 3 4]
 [3 1 2]
 [0 1 3]
 [2 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [23]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [24]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [25]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)

array([[0.04573493, 0.27579449, 0.17142526, 0.0328093 , 0.31702971,
        0.49209276, 0.44451019, 0.08474017, 0.15179989, 0.03780253],
       [0.0789641 , 0.47617568, 0.29597597, 0.05664722, 0.54737076,
        0.84962759, 0.76747343, 0.14630898, 0.2620916 , 0.06526833],
       [0.00715808, 0.04316525, 0.02683017, 0.00513506, 0.04961907,
        0.0770186 , 0.06957134, 0.01326289, 0.02375856, 0.00591656],
       [0.02925418, 0.1764109 , 0.10965152, 0.02098634, 0.20278685,
        0.31476527, 0.28432925, 0.05420373, 0.09709823, 0.02418024],
       [0.02984926, 0.17999943, 0.11188203, 0.02141325, 0.20691191,
        0.32116818, 0.29011304, 0.05530634, 0.09907339, 0.02467212],
       [0.08508848, 0.51310744, 0.31893159, 0.06104073, 0.58982434,
        0.91552394, 0.82699798, 0.15765657, 0.28241918, 0.07033048],
       [0.01341521, 0.08089746, 0.05028334, 0.00962379, 0.09299279,
        0.14434319, 0.13038602, 0.02485642, 0.04452673, 0.01108843],
       [0.08106905, 0.48886914, 0.3038658

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [26]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [27]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [28]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17725606  0.15817163]
